version: '3.6'
services:

  mongo:
    image: mongo:5.0
    deploy:
      placement:
        constraints:
          - node.labels.reliability == high
    volumes:
      - mongo_data:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  post:
    image: $USER_NAME/post
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 300M
      mode: replicated
      replicas: 3
      update_config:
        delay: 10s
        parallelism: 2
        failure_action: rollback
        order: start-first
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 1s    
    networks:
      - front_net
      - back_net

  comment:
    image: $USER_NAME/comment
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 300M
      mode: replicated
      replicas: 3
      update_config:
        delay: 10s
        parallelism: 2
        failure_action: rollback
        order: start-first
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        max_attempts: 10
        delay: 1s
    networks:
      - front_net
      - back_net

  ui:
    image: $USER_NAME/ui
    environment:
      - ENV=DEV
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 150M
      mode: replicated
      replicas: 3
      update_config:
        delay: 5s
        parallelism: 1
        failure_action: rollback
        order: start-first
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 3s
    ports:
      - "9292:9292/tcp"
    networks:
      - front_net

  node-exporter:
    image: prom/node-exporter:v0.15.0
    deploy:
      mode: global
    user: root
    networks:
      - back_net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

volumes:
  mongo_data: {}

networks:
  back_net: {}
  front_net: {}