{
 "title": "UI HTTP Requests",
 "time": { "from": "2023-03-12T19:38:43.497Z", "to": "2023-03-12T19:42:53.995Z" },
 "panels": [
  {
   "title": "Business_Logic_Monitoring_Comment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(comment_count[1h])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Requests with errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Business_Logic_Monitoring_Post",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(post_count[1h])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP response time 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_latency_seconds_bucket[5m])) by (le)) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UI_SERVICE_MONITORING",
   "type": "timeseries",
   "description": "All http requests that ui service receives",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ui_request_count{instance=\"ui:9292\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}